### PR TITLE
Add support for the language_in and language_out compiler options

### PR DESCRIPTION
**Pull request by acornett**
Add support to set the language_in and language_out compiler options from the plugin configuration.

### CODE REVIEW

**Comment by jlgrock** [comment]
Hey, this looks good.  I just want to test it out a bit (just to make sure) and I'll push out a dot release

**Comment by lukas-vlcek** [comment]
Nice :smile:

**Comment by acornett** [comment]
Thanks, let me know if you find any issues!

**Comment by jlgrock** [comment]
k, code was released.  I had to make a few changes just because of how JDK8 and the maven-plugin-plugin worked, but otherwise looked good.

**Comment by jlgrock** [comment]
oh, btw that should hit maven central by tomorrow morning.  Thanks!

**Pull request merged**
